spring:
  application:
    name: api-forumhub-challenge
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${url}:${port}/${db_name}
    username: ${db_username}
    password: ${db_password}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true