CREATE TABLE resposta(
    ID SERIAL PRIMARY KEY,
    MENSAGEM VARCHAR NOT NULL,
    DATA_CRIACAO DATE NOT NULL,
    SOLUCAO VARCHAR
);

CREATE TABLE usuario (
    id SERIAL PRIMARY KEY ,
    nome VARCHAR NOT NULL ,
    email VARCHAR UNIQUE NOT NULL,
    senha VARCHAR NOT NULL
);

CREATE TABLE curso (
    id SERIAL PRIMARY KEY ,
    nome VARCHAR NOT NULL ,
    categoria VARCHAR NOT NULL
);

CREATE TABLE perfil(
    id SERIAL PRIMARY KEY,
    nome VARCHAR NOT NULL UNIQUE
);